console.log("Oi, meu nome é André")
console.log('Eu queria comprar um carro')
console.log(`Teste`)
console.log("Infinity")
console.log(Infinity)
console.log()
console.log(typeof "Oi, meu nome é André")
console.log(typeof 'Eu queria comprar um carro')
console.log(typeof `Teste`)
console.log(typeof "Infinity")
console.log(typeof Infinity)