console.log("Primera linha \n Segunda linha")
console.log("O meu nome é 'André'")
console.log('O meu nome é "André"')
console.log(`A multiplicação de 5 por 3 é ${5*3}`)
console.log("O " + "meu " + "nome " + "é " + "André")