console.log( 5 > 3 && 3 == 2)
console.log(5 > 3 || 3 == 1)
console.log()
console.log(3 == 3 && "André" == "André")
console.log("André" == "Guilherme" || false)
console.log()
console.log(!(true && true))
console.log()
console.log(true && true)
console.log(false || false)